// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMwDdJZm7NWpd-jMuvwKcdas5gfIRXXQ4',
    appId: '1:774688698032:web:1bf5e63d90821a744cd575',
    messagingSenderId: '774688698032',
    projectId: 'asiapp-994a7',
    authDomain: 'asiapp-994a7.firebaseapp.com',
    storageBucket: 'asiapp-994a7.firebasestorage.app',
    measurementId: 'G-D0NFMBFHYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn_TbNKE1u446OS4txsnXdBVPGAwKi3ag',
    appId: '1:774688698032:android:d1fec3b892b821d14cd575',
    messagingSenderId: '774688698032',
    projectId: 'asiapp-994a7',
    storageBucket: 'asiapp-994a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ex6SPl1tjmUX4cDQvp5B6sv_p0MaWkQ',
    appId: '1:774688698032:ios:854c1d3cf12e82684cd575',
    messagingSenderId: '774688698032',
    projectId: 'asiapp-994a7',
    storageBucket: 'asiapp-994a7.firebasestorage.app',
    iosClientId: '774688698032-f3952hm0qne8qktqi9hrgmkmjlv2jqkq.apps.googleusercontent.com',
    iosBundleId: 'br.com.asimovjr.asiappMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ex6SPl1tjmUX4cDQvp5B6sv_p0MaWkQ',
    appId: '1:774688698032:ios:854c1d3cf12e82684cd575',
    messagingSenderId: '774688698032',
    projectId: 'asiapp-994a7',
    storageBucket: 'asiapp-994a7.firebasestorage.app',
    iosClientId: '774688698032-f3952hm0qne8qktqi9hrgmkmjlv2jqkq.apps.googleusercontent.com',
    iosBundleId: 'br.com.asimovjr.asiappMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMwDdJZm7NWpd-jMuvwKcdas5gfIRXXQ4',
    appId: '1:774688698032:web:859c8ea19996c64a4cd575',
    messagingSenderId: '774688698032',
    projectId: 'asiapp-994a7',
    authDomain: 'asiapp-994a7.firebaseapp.com',
    storageBucket: 'asiapp-994a7.firebasestorage.app',
    measurementId: 'G-DVFW7Y9YJX',
  );
}
